function run_cifar_s2(bits, varargin)
% CIFAR-10 experiment, setting 2

if nargin < 1, bits = 32; end
assert(ismember(bits, [16 24 32 48]), 'unexpected num. of bits');

if bits >= 32, bins = bits/2; end

demo.AP('cifar', bits, 'vggf', ...
    'split'        , 2       , ...
    'nbins'        , bins    , ...
    'gamma'        , [1 0 0] , ...
    'lrmult'       , 0.1     , ...
    'lr'           , 1e-2    , ...
    'lrdecay'      , 0       , ...
    'wdecay'       , 5e-4    , ...
    'batchsize'    , 250     , ...
    'epochs'       , 50      , ...
    'testInterval' , 20      , ...
    'gpus'         , 0       , ...
    varargin{:});

end
