function run_nuswide_NDCG(bits, varargin)
if nargin < 1, bits = 32; end
assert(ismember(bits, [16 32 48 64]), 'unexpected num. of bits');

demo.NDCG('nus', bits, 'vggf', ...
    'nbins'        , bits/2  , ...
    'gamma'        , [1 0 0] , ...
    'lrmult'       , 0.01    , ...
    'lr'           , 0.01    , ...
    'lrdecay'      , 0       , ...
    'wdecay'       , 5e-4    , ...
    'batchsize'    , 256     , ...
    'epochs'       , 50      , ...
    'testInterval' , 20      , ...
    'gpus'         , 0       , ...
    varargin{:});

end
