function run_imagenet(bits, varargin)
if nargin < 1, bits = 32; end
assert(ismember(bits, [16 32 48 64]), 'unexpected num. of bits');

demo.imagenet(bits , ...
    'nbins'        , 16       , ...
    'gamma'        , [10 0 0] , ...
    'lrmult'       , 0.01     , ...
    'lr'           , 0.05     , ...
    'lrdecay'      , 0.05     , ...
    'lrstep'       , 100      , ...
    'wdecay'       , 5e-4     , ...
    'batchsize'    , 256      , ...
    'epochs'       , 125      , ...
    'testInterval' , 25       , ...
    'gpus'         , 0        , ...
    varargin{:});

end
